modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "manas_cosmetics"
version = "${version}"
displayName = "Manas Cosmetics"
authors = "ManasMods"
description = '''
A full server cosmetics mod for ManasMods' Minecraft 1.21.1 server.
'''
#logoFile = ""

[[dependencies.manas_cosmetics]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.manas_cosmetics]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.manas_cosmetics]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.manas_cosmetics]]
modId = "tensura"
type = "optional"
versionRange = "[2.0,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "manas_cosmetics.mixins.json"
